blank_issues_enabled: false
contact_links:
  - name: Translations
    about: If you noticed that something is wrong use this link.
    url: https://app.lokalise.com/public/2728010065b52d190d6247.58782749/
